<?php

namespace ApiBundle\Repository;

/**
 * entrenadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entrenadorRepository extends \Doctrine\ORM\EntityRepository
{
}
